apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-app
  namespace: store
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gateway
  endpoints:
    - port: http
      path: /management/prometheus
